server:
  port: 9001
#服务名称
spring:
  application:
    name: api-geteway
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    order-service: /apigeteway/order/**
    product-service: /apigeteway/product/**
  #忽略某个服务
  #ignored-services: product-service
  ignored-patterns: /*-service/**
  sensitive-headers:

